version: "1.0"
services:
  anylist:
    image: kevdliu/anylist:latest
    container_name: anylist
    environment:
      PORT: 9000
      # EMAIL: <Anylist account email>
      # PASSWORD: <Anylist account password>
      # DEFAULT_LIST: <Optional name of default list>
    volumes:
      - anylist-data:/data
    ports:
      - 9000:9000
    restart: unless-stopped
volumes:
  anylist-data:
